GRANT CONNECT ON DATABASE plannerdb TO planner_api;

-- Create schema planner owned by planner_api
CREATE SCHEMA IF NOT EXISTS planner;

REVOKE CREATE ON SCHEMA planner FROM planner_api;
REVOKE ALL ON SCHEMA planner FROM planner_api;
GRANT USAGE ON SCHEMA planner TO planner_api;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE, TRIGGER, REFERENCES ON ALL TABLES IN SCHEMA planner TO planner_api;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA planner TO planner_api;
GRANT EXECUTE ON ALL ROUTINES IN SCHEMA planner TO planner_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA planner GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO planner_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA planner GRANT USAGE, SELECT ON SEQUENCES TO planner_api;
ALTER DEFAULT PRIVILEGES IN SCHEMA planner GRANT EXECUTE ON ROUTINES TO planner_api;